### ISSUE TITLE
缺少未知包

### ISSUE THREAD

**Issue by engigu** [0honus0/python-CuteCat-iHttp#8]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\test.py", line 1, in <module>
    from CuteCat import CuteCat
  File "C:\ProgramData\Miniconda3\lib\site-packages\CuteCat\__init__.py", line 9
, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'

![image](https://user-images.githubusercontent.com/24751376/165709789-fca26848-62c7-43c4-9e8a-c6cb5989f243.png)

**Comment by 0honus0** [comment]
pip3 install python-magic
